print("Raj and 5 friends birthdays!!!")
Raj =("December 25")
Amir =("January 1")
Rohit =("August 15")
Sreene =("March 20")
Ishaan =("July 10")
Nirbhays =("May 9")

print("Raj's birthday is on:", Raj)
print("Amir's birthday is on:", Amir)
print("Rohit's birthday is on:", Rohit)
print("Sreene's birthday is on:", Sreene)
print("Ishaan's birthday is on:", Ishaan)
print("Nirbhays's birthday is on:", Nirbhays)